#! /bin/sh

pgrep -x sxhkd >> /dev/null || sxhkd &

$HOME/.config/polybar/launch.sh

nitrogen --restore 
picom &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           15

bspc config split_ratio          1
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color '#A1B19F'

bspc rule -a firefox desktop='^2' 
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a obsidian desktop='^3'
bspc rule -a Chromium desktop='^3'
bspc rule -a mplayer2 state=floating
bspc rule -a arkanoix state=floating 
bspc rule -a Zathura state=tiled

syncthing
