#!/bin/bash

mode=$1
filepath=$2

for counter in {0..7};
do
  day=$(date "+<%Y-%m-%d %a>" --date=$counter+" day")
  echo "[___"$day '(+'$counter"d)___]"
  if [ $mode == "SSC" ]; then
    grep -E 'TODO.+SCHEDULED: '+"$day" -n $filepath | sed -e $'s/TODO/'$'\e[31m''&'$'\e[0m/g' \
               -e $'s/DONE/'$'\e[32m''&'$'\e[0m/g' \
               -e $'s/:.*:/'$'\e[35m''&'$'\e[0m/g' \
               -e $'s/SCHEDULED/'$'\e[32m''&'$'\e[0m/g'
  elif [ $mode == "SDD" ]; then
    grep -E 'TODO.+DEADLINE: '+"$day" -n $filepath | sed -e $'s/TODO/'$'\e[31m''&'$'\e[0m/g' \
               -e $'s/DONE/'$'\e[32m''&'$'\e[0m/g' \
               -e $'s/:.*:/'$'\e[35m''&'$'\e[0m/g' \
               -e $'s/DEADLINE/'$'\e[31m''&'$'\e[0m/g'
  fi
  echo -----------------------------------------------------
  echo 
done

